spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onjeong?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    hikari:
      maximum-pool-size: 180 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

kakao:
  REST_KEY: "475bd7a6a8dc9f061055c6f827ab4b25"
  REDIRECT_URI: "http://10.0.2.2:8080/auth/kakao/redirect"

jwt:
  secret_key: "onjeong-jwt-secret-key-made-by-seheon"
  issuer: "quwe153@naver.com"

phone:
  API_KEY: "NCSVYKYPPACZYSME"
  API_SECRET_KEY: "TJIYE8TQWO1ZW6MYDUO89LFKJGZKA97H"
  DOMAIN: "https://api.coolsms.co.kr"

cloud:
  aws:
    credentials:
      accessKey: AKIA47DE5JTIDAD72GXT
      secretKey: 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
    s3:
      bucket: allfriend
      dir: /allfriend
    region:
      static: ap-northeast-2
    stack:
      auto: false

openvidu:
  url: https://i10a503.p.ssafy.io/
  secret: MY_SECRET

firebase:
  config: onjeong-firebase-admin-sdk.json
  project:
    id: onjeong-7bc7a

weather:
  API_KEY: y227EU54aeGEvJWgRtZ%2B5QIY5a3MMabhlk8oUMtFt6qrgwHVWZwBqw3Q9tO4KHCMD6QavaZUsMr7B%2FydM2Xigw%3D%3D

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace